import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { dialog } from '../src/lib/dialog';
import { Screen } from '../src/components/Screen';
import { BodyText, Card, Pill, PrimaryActionLabel, ScreenTitle, SectionTitle, SupportText, ui } from '../src/components/ui';
import { listAutomationJobs, listAutomationRules, processDueAutomations, seedAutomationDefaults, updateAutomationRule, type AutomationJob, type AutomationRule } from '../src/lib/automations';
import { getActiveWorkspace } from '../src/lib/workspace';

export default function AutomationsScreen(){
  const[workspaceId,setWorkspaceId]=useState<string|null>(null);const[rules,setRules]=useState<AutomationRule[]>([]);const[jobs,setJobs]=useState<AutomationJob[]>([]);const[busy,setBusy]=useState(true);
  useEffect(()=>{void load();},[]);async function load(){setBusy(true);try{const workspace=await getActiveWorkspace();setWorkspaceId(workspace.id);let nextRules=await listAutomationRules(workspace.id);if(!nextRules.length)nextRules=await seedAutomationDefaults(workspace.id);setRules(nextRules);setJobs(await listAutomationJobs(workspace.id));}catch(error){void dialog.notify('Could not load automations',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  async function toggle(rule:AutomationRule){if(!workspaceId)return;setBusy(true);try{await updateAutomationRule(workspaceId,rule.id,{enabled:!rule.enabled});await load();}catch(error){void dialog.notify('Could not update automation',error instanceof Error?error.message:'Unknown error');setBusy(false);}}
  async function processDue(){if(!workspaceId)return;setBusy(true);try{await processDueAutomations(workspaceId);await load();}catch(error){void dialog.notify('Automation run failed',error instanceof Error?error.message:'Unknown error');setBusy(false);}}
  const enabledCount=rules.filter((rule)=>rule.enabled).length;const failedCount=jobs.filter((job)=>job.status==='failed').length;
  return <Screen>
    <Pill tone="gold">Owner-Controlled Workflows</Pill><ScreenTitle>Automations</ScreenTitle><SupportText>Predictable work only. Delayed actions recheck the current business state before running.</SupportText>
    <Card premium><View style={styles.summary}><View style={styles.summaryItem}><SupportText>Active rules</SupportText><Text style={styles.stat}>{enabledCount}</Text></View><View style={styles.summaryItem}><SupportText>Needs review</SupportText><Text style={[styles.stat,failedCount>0&&{color:ui.colors.critical}]}>{failedCount}</Text></View></View><BodyText>Client-facing actions remain approval-aware and every run must report success or failure honestly.</BodyText></Card>
    {busy?<Card><BodyText>Loading automations...</BodyText></Card>:null}
    <Card><SectionTitle>Automation rules</SectionTitle>{rules.map((rule)=><View key={rule.id} style={styles.rule}><View style={styles.ruleCopy}><View style={styles.ruleHeader}><Text style={styles.ruleTitle}>{rule.name}</Text><Pill tone={rule.enabled?'success':'secondary'}>{rule.enabled?'active':'off'}</Pill></View><SupportText>{humanize(rule.trigger_type)} → {humanize(rule.action_type)}</SupportText>{rule.delay_minutes>0?<SupportText>Waits {rule.delay_minutes} minutes, then rechecks current state.</SupportText>:<SupportText>Runs only after current-state and approval checks.</SupportText>}</View><Switch value={rule.enabled} disabled={busy} trackColor={{false:ui.colors.border,true:ui.colors.softGold}} thumbColor={rule.enabled?ui.colors.gold:ui.colors.secondaryText} onValueChange={()=>void toggle(rule)}/></View>)}</Card>
    <Card premium><Pill tone="warning">Safe execution</Pill><SectionTitle>Process due jobs</SectionTitle><SupportText>This prototype action processes eligible due jobs. Canceled or changed business states stop stale work, and duplicate protection stays active.</SupportText><Pressable disabled={busy} onPress={()=>void processDue()}><PrimaryActionLabel>{busy?'Working...':'Process Due Jobs'}</PrimaryActionLabel></Pressable></Card>
    <Card><SectionTitle>Recent jobs</SectionTitle>{jobs.slice(0,10).map((job)=><View key={job.id} style={styles.job}><View style={styles.jobCopy}><Text style={styles.ruleTitle}>{job.rule?.name??'Automation'}</Text><SupportText>{new Date(job.scheduled_for).toLocaleString()}</SupportText>{job.last_error?<SupportText tone="critical">{job.last_error}</SupportText>:null}</View><Pill tone={job.status==='completed'?'success':job.status==='failed'?'critical':job.status==='canceled'?'secondary':'warning'}>{humanize(job.status)}</Pill></View>)}{!jobs.length?<SupportText>No automation jobs yet.</SupportText>:null}</Card>
    <Card><SectionTitle>What never runs silently</SectionTitle><SupportText>Complaints, refunds, disputes, exceptional pricing, medical concerns, uncertain recommendations, schedule conflicts, public publishing and sensitive client messages remain owner-controlled.</SupportText></Card>
  </Screen>;
}
function humanize(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,(c)=>c.toUpperCase())}
const styles=StyleSheet.create({summary:{flexDirection:'row',gap:ui.spacing.md},summaryItem:{flex:1,gap:2},stat:{color:ui.colors.primaryText,fontSize:28,fontWeight:'700'},rule:{flexDirection:'row',alignItems:'center',gap:ui.spacing.sm,paddingVertical:ui.spacing.sm,borderBottomWidth:1,borderBottomColor:ui.colors.border},ruleCopy:{flex:1,gap:ui.spacing.xs},ruleHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:ui.spacing.xs},ruleTitle:{color:ui.colors.primaryText,fontSize:16,fontWeight:'700',flexShrink:1},job:{flexDirection:'row',alignItems:'center',gap:ui.spacing.sm,paddingVertical:ui.spacing.xs,borderBottomWidth:1,borderBottomColor:ui.colors.border},jobCopy:{flex:1,gap:2}});
