import { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { dialog } from '../src/lib/dialog';
import { Screen } from '../src/components/Screen';
import { BodyText, Card, Pill, PrimaryActionLabel, ScreenTitle, SectionTitle, SupportText, ui } from '../src/components/ui';
import { submitBetaFeedback } from '../src/lib/beta';
import { getActiveWorkspace } from '../src/lib/workspace';

const categories = [['friction','Something slowed me down'],['bug','Something broke'],['idea','I have an idea'],['success','AngelOS helped me'],['testimonial_candidate','I want to share a review']] as const;

export default function BetaFeedbackScreen() {
  const [category,setCategory]=useState<(typeof categories)[number][0]>('friction');
  const [message,setMessage]=useState('');const[rating,setRating]=useState(5);const[contact,setContact]=useState(false);const[quote,setQuote]=useState(false);const[busy,setBusy]=useState(false);
  async function submit(){if(!message.trim())return;setBusy(true);try{const workspace=await getActiveWorkspace();await submitBetaFeedback(workspace.id,{category,message:message.trim(),rating,permissionToContact:contact,permissionToQuote:category==='testimonial_candidate'?quote:false});setMessage('');setQuote(false);void dialog.notify('Feedback sent','Thank you. It stays private unless you explicitly allowed your review to be quoted.');}catch(error){void dialog.notify('Could not send feedback',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  return <Screen><View style={styles.stack}>
    <Pill tone="gold">Private Beta</Pill><ScreenTitle>Help shape AngelOS</ScreenTitle><SupportText>Tell us what helped, what broke, or what felt frustrating. Small details help improve the system before wider release.</SupportText>
    <Card><SectionTitle>What happened?</SectionTitle><View style={styles.choices}>{categories.map(([value,label])=><Pressable key={value} onPress={()=>{setCategory(value);if(value!=='testimonial_candidate')setQuote(false);}} style={[styles.choice,category===value&&styles.selected]}><Text style={[styles.choiceText,category===value&&styles.selectedText]}>{label}</Text></Pressable>)}</View></Card>
    <Card premium><SectionTitle>Your feedback</SectionTitle><TextInput multiline value={message} onChangeText={setMessage} placeholder="Tell us what happened and what you expected." placeholderTextColor={ui.colors.secondaryText} style={styles.input}/><View style={styles.ratingHeader}><BodyText>Overall today</BodyText><Pill tone="gold">{rating}/5</Pill></View><View style={styles.ratingRow}>{[1,2,3,4,5].map(value=><Pressable key={value} onPress={()=>setRating(value)} style={[styles.rating,rating===value&&styles.ratingSelected]}><Text style={styles.ratingText}>{value}</Text></Pressable>)}</View></Card>
    <Card><SectionTitle>Permission stays separate</SectionTitle><View style={styles.toggle}><View style={styles.toggleCopy}><BodyText>Angel may contact me</BodyText><SupportText>Only to understand this feedback better.</SupportText></View><Switch value={contact} onValueChange={setContact} trackColor={{false:ui.colors.border,true:ui.colors.softGold}} thumbColor={contact?ui.colors.gold:ui.colors.secondaryText}/></View>{category==='testimonial_candidate'?<View style={styles.toggle}><View style={styles.toggleCopy}><BodyText>Allow a public quote</BodyText><SupportText>Off by default. Ordinary feedback remains private.</SupportText></View><Switch value={quote} onValueChange={setQuote} trackColor={{false:ui.colors.border,true:ui.colors.softGold}} thumbColor={quote?ui.colors.gold:ui.colors.secondaryText}/></View>:null}</Card>
    <Pressable disabled={busy||!message.trim()} onPress={()=>void submit()} style={({pressed})=>[(busy||!message.trim()||pressed)&&styles.muted]}><PrimaryActionLabel>{busy?'Sending...':'Send Private Feedback'}</PrimaryActionLabel></Pressable>
  </View></Screen>;
}

const styles=StyleSheet.create({stack:{gap:ui.spacing.md},choices:{gap:ui.spacing.xs},choice:{minHeight:48,justifyContent:'center',borderWidth:1,borderColor:ui.colors.border,borderRadius:ui.radius.control,paddingHorizontal:ui.spacing.sm,backgroundColor:ui.colors.elevated},selected:{borderColor:ui.colors.gold,backgroundColor:ui.colors.softGold},choiceText:{color:ui.colors.primaryText,fontSize:15,fontWeight:'600'},selectedText:{fontWeight:'700'},input:{minHeight:130,borderWidth:1,borderColor:ui.colors.border,borderRadius:ui.radius.control,padding:ui.spacing.sm,color:ui.colors.primaryText,backgroundColor:ui.colors.elevated,fontSize:16,textAlignVertical:'top'},ratingHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},ratingRow:{flexDirection:'row',gap:ui.spacing.xs},rating:{flex:1,height:46,borderWidth:1,borderColor:ui.colors.border,borderRadius:ui.radius.control,alignItems:'center',justifyContent:'center',backgroundColor:ui.colors.elevated},ratingSelected:{borderColor:ui.colors.gold,backgroundColor:ui.colors.softGold},ratingText:{color:ui.colors.primaryText,fontWeight:'700'},toggle:{flexDirection:'row',alignItems:'center',gap:ui.spacing.sm,paddingVertical:ui.spacing.xs,borderBottomWidth:1,borderBottomColor:ui.colors.border},toggleCopy:{flex:1,gap:2},muted:{opacity:.55}});
