import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { Screen } from '../src/components/Screen';
import { Button, Card, ScreenTitle, SupportText, TextField, ui } from '../src/components/ui';
import { supabase } from '../src/lib/supabase';
export default function ResetPasswordScreen() { const { t } = useTranslation(); const params = useLocalSearchParams<{ code?: string }>(); const [password, setPassword] = useState(''); const [repeat, setRepeat] = useState(''); const [error, setError] = useState(''); const [ready, setReady] = useState(false); useEffect(() => { void prepare(); }, []); async function prepare() { if (params.code) { const result = await supabase.auth.exchangeCodeForSession(params.code); if (result.error) setError(t('auth.linkExpired')); else setReady(true); return; } const url = await import('expo-linking').then((Linking) => Linking.getInitialURL()); const fragment = new URLSearchParams(url?.split('#')[1] ?? ''); const accessToken = fragment.get('access_token'); const refreshToken = fragment.get('refresh_token'); if (accessToken && refreshToken) { const result = await supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken }); if (result.error) setError(t('auth.linkExpired')); else setReady(true); } else setError(t('auth.linkExpired')); } async function save() { if (password.length < 8) return setError(t('auth.min8')); if (password !== repeat) return setError(t('auth.noMatch')); const result = await supabase.auth.updateUser({ password }); if (result.error) return setError(result.error.message); router.replace('/'); } return <Screen><ScreenTitle>{t('auth.chooseNew')}</ScreenTitle><Card>{ready ? <><TextField label={t('auth.newPassword')} secure autoComplete="new-password" value={password} onChangeText={setPassword} hint={t('account.passwordHint')} /><TextField label={t('auth.repeatPassword')} secure autoComplete="new-password" value={repeat} onChangeText={setRepeat} /><Button label={t('auth.save')} onPress={() => void save()} /></> : null}{error ? <SupportText tone="critical">{error}</SupportText> : null}</Card></Screen>; }
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: ui.colors.border, borderRadius: ui.radius.control, padding: ui.spacing.sm, color: ui.colors.primaryText, marginBottom: ui.spacing.sm } });
