import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { dialog } from '../src/lib/dialog';
import { Screen } from '../src/components/Screen';
import { BodyText, Card, Pill, PrimaryActionLabel, ScreenTitle, SecondaryActionLabel, SectionTitle, SupportText, ui } from '../src/components/ui';
import { cancelSubscription, getSubscription, reactivateDemo, redeemStudentDiscount, requestCheckout, type SubscriptionStatus } from '../src/lib/subscription';
import { getActiveWorkspace } from '../src/lib/workspace';

export default function SubscriptionScreen() {
  const [workspaceId,setWorkspaceId]=useState<string|null>(null); const [status,setStatus]=useState<SubscriptionStatus|null>(null); const [interval,setInterval]=useState<'monthly'|'yearly'>('monthly'); const [studentToken,setStudentToken]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{void load();},[]);
  async function load(){try{const workspace=await getActiveWorkspace();setWorkspaceId(workspace.id);const data=await getSubscription(workspace.id);setStatus(data);setInterval(data.subscription.billing_interval);}catch(error){void dialog.notify('Could not load subscription',error instanceof Error?error.message:'Unknown error');}}
  async function checkout(){if(!workspaceId)return;setBusy(true);try{const result=await requestCheckout(workspaceId,interval);if(result.checkout.mode==='not_configured')void dialog.notify('Payment setup coming next',result.checkout.message);else void dialog.notify('Checkout ready','Open the secure payment checkout.');}catch(error){void dialog.notify('Could not start checkout',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  async function demo(){if(!workspaceId)return;setBusy(true);try{await reactivateDemo(workspaceId,interval);await load();}catch(error){void dialog.notify('Demo activation unavailable',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  async function redeem(){if(!workspaceId||!studentToken.trim())return;setBusy(true);try{await redeemStudentDiscount(workspaceId,studentToken.trim());setStudentToken('');await load();}catch(error){void dialog.notify('Could not apply student discount',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  async function cancel(){if(!workspaceId)return;const ok=await dialog.confirm({title:'Cancel AngelOS?',message:'Your workspace will switch to read-only for 60 days. You can view, export or reactivate during that period.',cancelText:'Keep subscription',confirmText:'Cancel subscription',destructive:true});if(!ok)return;try{await cancelSubscription(workspaceId);await load();}catch(error){void dialog.notify('Could not cancel',error instanceof Error?error.message:'Unknown error');}}
  if(!status)return <Screen><Card><BodyText>Loading subscription...</BodyText></Card></Screen>;
  const price=interval==='yearly'?status.plan.yearly_price_cents:status.plan.monthly_price_cents; const final=Math.round(price*(100-status.subscription.discount_percent)/100); const active=!['read_only','expired'].includes(status.subscription.status);
  return <Screen>
    <Pill tone="gold">Account Access</Pill><ScreenTitle>Subscription</ScreenTitle><SupportText>Your plan, discount and workspace-access protection in one place.</SupportText>
    <Card premium><View style={styles.statusHeader}><View style={styles.statusCopy}><SupportText>Current status</SupportText><Text style={styles.status}>{humanize(status.subscription.status)}</Text></View><Pill tone={active?'success':'warning'}>{active?'Full access':'Protected access'}</Pill></View><BodyText>{status.access.reason??'Full business access is available.'}</BodyText>{status.subscription.trial_ends_at&&status.subscription.status==='trialing'?<SupportText>Trial ends {new Date(status.subscription.trial_ends_at).toLocaleDateString()}</SupportText>:null}{status.subscription.read_only_until?<SupportText>Read-only access until {new Date(status.subscription.read_only_until).toLocaleDateString()}</SupportText>:null}</Card>
    <Card><SectionTitle>Your plan</SectionTitle><View style={styles.segmentRow}>{(['monthly','yearly'] as const).map((value)=><Pressable key={value} onPress={()=>setInterval(value)} style={[styles.segment,interval===value&&styles.selected]}><Text style={styles.segmentText}>{value==='monthly'?'Monthly':'Yearly'}</Text></Pressable>)}</View><Text style={styles.price}>{money(final,status.plan.currency)}<Text style={styles.priceUnit}>{interval==='monthly'?'/month':'/year'}</Text></Text>{status.subscription.discount_percent?<Pill tone="success">{status.subscription.discount_percent}% student discount applied</Pill>:<SupportText>14-day public trial | $49/month or $490/year</SupportText>}<Pressable disabled={busy} onPress={()=>void checkout()}><PrimaryActionLabel>{busy?'Working...':status.subscription.status==='active'?'Manage Plan':'Upgrade or Reactivate'}</PrimaryActionLabel></Pressable>{!status.billingProvider.configured?<Pressable disabled={busy} onPress={()=>void demo()}><SecondaryActionLabel>Activate Demo Plan</SecondaryActionLabel></Pressable>:null}</Card>
    <Card><SectionTitle>Angels Beauty student discount</SectionTitle><SupportText>Verified students and alumni receive an ongoing private 20% discount unless program terms change later.</SupportText><TextInput value={studentToken} onChangeText={setStudentToken} placeholder="Private student token" placeholderTextColor={ui.colors.secondaryText} autoCapitalize="none" style={styles.input}/><Pressable disabled={busy||!studentToken.trim()} onPress={()=>void redeem()}><SecondaryActionLabel>Apply Student Discount</SecondaryActionLabel></Pressable></Card>
    <Card premium><SectionTitle>Your data stays protected</SectionTitle><BodyText>Cancellation does not immediately erase your business records. Your workspace remains read-only for 60 days so you can view, export or reactivate.</BodyText></Card>
    {active?<Pressable onPress={()=>void cancel()} disabled={busy}><Text style={styles.danger}>Cancel subscription</Text></Pressable>:null}
  </Screen>;
}
function money(cents:number,currency:string){return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100)} function humanize(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,(c)=>c.toUpperCase())}
const styles=StyleSheet.create({statusHeader:{flexDirection:'row',alignItems:'flex-start',gap:ui.spacing.sm},statusCopy:{flex:1,gap:2},status:{color:ui.colors.primaryText,fontSize:27,fontWeight:'700'},segmentRow:{flexDirection:'row',gap:ui.spacing.xs},segment:{flex:1,borderWidth:1,borderColor:ui.colors.border,borderRadius:ui.radius.control,padding:12,alignItems:'center',backgroundColor:ui.colors.elevated},selected:{borderColor:ui.colors.gold,backgroundColor:ui.colors.softGold},segmentText:{color:ui.colors.primaryText,fontSize:15,fontWeight:'700'},price:{color:ui.colors.primaryText,fontSize:30,fontWeight:'700'},priceUnit:{color:ui.colors.secondaryText,fontSize:15,fontWeight:'400'},input:{borderWidth:1,borderColor:ui.colors.border,borderRadius:ui.radius.control,backgroundColor:ui.colors.elevated,color:ui.colors.primaryText,padding:ui.spacing.sm,fontSize:16},danger:{color:ui.colors.critical,fontSize:15,fontWeight:'700',textAlign:'center',paddingVertical:ui.spacing.sm}});
