import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { dialog } from '../src/lib/dialog';
import { Screen } from '../src/components/Screen';
import { BodyText, Card, Pill, PrimaryActionLabel, ScreenTitle, SectionTitle, SupportText, ui } from '../src/components/ui';
import { acknowledgeAttention, getSystemHealth, runSystemHealthCheck, updateOperationalControls, type SystemHealthOverview } from '../src/lib/system-health';
import { getActiveWorkspace } from '../src/lib/workspace';

export default function SystemHealthScreen(){
  const[workspaceId,setWorkspaceId]=useState<string|null>(null);const[overview,setOverview]=useState<SystemHealthOverview|null>(null);const[busy,setBusy]=useState(false);
  useEffect(()=>{void load(false);},[]);
  async function load(runCheck:boolean){try{setBusy(true);const workspace=await getActiveWorkspace();setWorkspaceId(workspace.id);setOverview(runCheck?await runSystemHealthCheck(workspace.id):await getSystemHealth(workspace.id));}catch(error){void dialog.notify('Could not load system health',error instanceof Error?error.message:'Unknown error');}finally{setBusy(false);}}
  async function setControl(key:'pauseAiActions'|'pauseAutomations'|'emergencyReadOnly',value:boolean){if(!workspaceId||!overview)return;try{setBusy(true);await updateOperationalControls(workspaceId,{[key]:value,reason:value?'Owner enabled from System Health':''});await load(true);}catch(error){void dialog.notify('Could not update control',error instanceof Error?error.message:'Unknown error');setBusy(false);}}
  async function acknowledge(id:string){if(!workspaceId)return;try{await acknowledgeAttention(workspaceId,id);await load(false);}catch(error){void dialog.notify('Could not acknowledge',error instanceof Error?error.message:'Unknown error');}}
  const openAttention=overview?.attention.filter((item)=>item.status!=='resolved')??[];
  return <Screen onRefresh={() => load(false)}>
    <Pill tone="gold">Safety Center</Pill><ScreenTitle>System Health</ScreenTitle><SupportText>See what works, what is affected, and what actually needs you.</SupportText>
    <Card premium><View style={styles.statusHeader}><View style={styles.statusCopy}><SupportText>Overall status</SupportText><Text style={styles.status}>{humanize(overview?.overallStatus??'unknown')}</Text></View><Pill tone={overview?.overallStatus==='healthy'?'success':overview?.counts.urgent?'critical':'warning'}>{overview?.counts.urgent??0} urgent</Pill></View><SupportText>{overview?`${overview.counts.today} today | ${overview.counts.later} later`:'Run a health check to verify the workspace.'}</SupportText><Pressable disabled={busy} onPress={()=>void load(true)}><PrimaryActionLabel>{busy?'Checking...':'Run Health Check'}</PrimaryActionLabel></Pressable></Card>
    {overview?<Card><SectionTitle>Emergency controls</SectionTitle><SupportText>Use these only when you need to pause business-changing activity.</SupportText><ControlRow label="Pause AI actions" detail="Chat stays available; AI cannot change business data." value={overview.controls.pause_ai_actions} disabled={busy} onValueChange={(value)=>void setControl('pauseAiActions',value)}/><ControlRow label="Pause automations" detail="Stops background jobs until you resume them." value={overview.controls.pause_automations} disabled={busy} onValueChange={(value)=>void setControl('pauseAutomations',value)}/><ControlRow label="Emergency read-only" detail="Highest safety mode. Business-changing backend actions stop." value={overview.controls.emergency_read_only} disabled={busy} critical onValueChange={(value)=>void setControl('emergencyReadOnly',value)}/></Card>:null}
    <Card><View style={styles.sectionHeader}><SectionTitle>Needs Attention</SectionTitle><Pill tone={openAttention.length?'warning':'success'}>{openAttention.length} open</Pill></View>{openAttention.map((item)=><View key={item.id} style={styles.item}><View style={styles.itemHeader}><Text style={styles.itemTitle}>{item.title}</Text><Pill tone={item.severity==='urgent'?'critical':item.severity==='today'?'warning':'secondary'}>{item.severity}</Pill></View><BodyText>{item.summary}</BodyText><SupportText>Status: {humanize(item.status)}</SupportText>{item.status==='open'?<Pressable onPress={()=>void acknowledge(item.id)}><Text style={styles.link}>Acknowledge</Text></Pressable>:null}</View>)}{!openAttention.length?<><SectionTitle>Nothing needs you</SectionTitle><SupportText>No unresolved owner action is currently recorded.</SupportText></>:null}</Card>
    <Card><SectionTitle>Connected components</SectionTitle>{overview?.components.map((component)=><View key={component.id} style={styles.item}><View style={styles.itemHeader}><Text style={styles.itemTitle}>{humanize(component.component)}{component.provider?` | ${humanize(component.provider)}`:''}</Text><Pill tone={component.status==='healthy'?'success':component.status==='disconnected'?'critical':'warning'}>{humanize(component.status)}</Pill></View><BodyText>{component.summary}</BodyText><SupportText>Last checked {new Date(component.last_checked_at).toLocaleString()}</SupportText></View>)}{!overview?.components.length?<SupportText>No verified health evidence yet. Run Health Check.</SupportText>:null}</Card>
  </Screen>;
}
function ControlRow({label,detail,value,disabled,critical=false,onValueChange}:{label:string;detail:string;value:boolean;disabled:boolean;critical?:boolean;onValueChange:(value:boolean)=>void}){return <View style={styles.control}><View style={styles.controlCopy}><Text style={[styles.itemTitle,critical&&{color:ui.colors.critical}]}>{label}</Text><SupportText>{detail}</SupportText></View><Switch value={value} disabled={disabled} trackColor={{false:ui.colors.border,true:critical?ui.colors.critical:ui.colors.softGold}} thumbColor={value?ui.colors.gold:ui.colors.secondaryText} onValueChange={onValueChange}/></View>}
function humanize(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,(c)=>c.toUpperCase())}
const styles=StyleSheet.create({statusHeader:{flexDirection:'row',alignItems:'flex-start',gap:ui.spacing.sm},statusCopy:{flex:1,gap:2},status:{color:ui.colors.primaryText,fontSize:27,fontWeight:'700'},sectionHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:ui.spacing.sm},item:{gap:ui.spacing.xs,paddingTop:ui.spacing.sm,borderTopWidth:1,borderTopColor:ui.colors.border},itemHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:ui.spacing.sm},itemTitle:{color:ui.colors.primaryText,fontSize:16,fontWeight:'700',flexShrink:1},control:{flexDirection:'row',alignItems:'center',gap:ui.spacing.sm,paddingVertical:ui.spacing.xs,borderBottomWidth:1,borderBottomColor:ui.colors.border},controlCopy:{flex:1,gap:2},link:{color:ui.colors.gold,fontSize:15,fontWeight:'700',paddingVertical:ui.spacing.xs}});
